# Generated by Django 5.0.7 on 2024-07-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_article_content_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.article'),
        ),
    ]
